version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  migration:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py update_rates"
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration

volumes:
  postgres_data:
